"""initial schema

Revision ID: c8461bc78170
Revises: 
Create Date: 2026-05-05 13:46:14.997801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'c8461bc78170'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'farmer', 'analyst', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('farms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_user_id'), 'farms', ['user_id'], unique=False)
    op.create_table('fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('crop_type', sa.String(length=100), nullable=True),
    sa.Column('planting_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('boundary_geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_farm_id'), 'fields', ['farm_id'], unique=False)
    op.create_table('irrigation_recs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('soil_moisture_pct', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.Enum('irrigate_now', 'irrigate_soon', 'adequate', 'overwatered', name='irrigation_status'), nullable=False),
    sa.Column('water_amount_mm', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irrigation_recs_field_id'), 'irrigation_recs', ['field_id'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('model_type', sa.Enum('crop_stress', 'irrigation', 'vra_zones', 'soil_assessment', name='model_type_enum'), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_field_id'), 'ml_predictions', ['field_id'], unique=False)
    op.create_table('satellite_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('sentinel2', 'landsat8', name='satellite_source'), nullable=False),
    sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('gee_asset_id', sa.String(length=500), nullable=True),
    sa.Column('bands_available', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellite_images_field_id'), 'satellite_images', ['field_id'], unique=False)
    op.create_table('yield_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('predicted_yield_tha', sa.Float(), nullable=False),
    sa.Column('yield_lower_bound', sa.Float(), nullable=True),
    sa.Column('yield_upper_bound', sa.Float(), nullable=True),
    sa.Column('estimated_harvest', sa.DateTime(timezone=True), nullable=True),
    sa.Column('harvest_readiness_pct', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yield_predictions_field_id'), 'yield_predictions', ['field_id'], unique=False)
    op.create_table('vegetation_indices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('ndvi', sa.Float(), nullable=True),
    sa.Column('evi', sa.Float(), nullable=True),
    sa.Column('ndwi', sa.Float(), nullable=True),
    sa.Column('ndre', sa.Float(), nullable=True),
    sa.Column('lai', sa.Float(), nullable=True),
    sa.Column('ndvi_min', sa.Float(), nullable=True),
    sa.Column('ndvi_max', sa.Float(), nullable=True),
    sa.Column('ndvi_std', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['satellite_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vegetation_indices_image_id'), 'vegetation_indices', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vegetation_indices_image_id'), table_name='vegetation_indices')
    op.drop_table('vegetation_indices')
    op.drop_index(op.f('ix_yield_predictions_field_id'), table_name='yield_predictions')
    op.drop_table('yield_predictions')
    op.drop_index(op.f('ix_satellite_images_field_id'), table_name='satellite_images')
    op.drop_table('satellite_images')
    op.drop_index(op.f('ix_ml_predictions_field_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_irrigation_recs_field_id'), table_name='irrigation_recs')
    op.drop_table('irrigation_recs')
    op.drop_index(op.f('ix_fields_farm_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_farms_user_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
